# ============================================================
# run_model.jl — Interactive Walkthrough of the Retinal Digital Twin
# ============================================================
#
# This script walks through the retinal column simulation step by step.
# Run it section by section in the Julia REPL, or all at once.
#
# Each section explains what is happening biologically and computationally.
# ============================================================

# --- Section 1: Setup ---
# Load the package. First time may take a moment to precompile.
using RetinalTwin

println("=" ^ 60)
println("  Retinal Digital Twin — Interactive Walkthrough")
println("=" ^ 60)

# --- Section 2: Build the Retinal Column ---
# The retinal column is the minimal vertical pathway from photoreceptors
# to ganglion cells. It contains 11 cell types with a total of ~193 ODEs.
#
# Population: 20 rods, 5 cones, 2 HCs, 1 ON-BC, 1 OFF-BC,
#             3 A2 amacrines, 3 GABA amacrines, 1 DA amacrine,
#             1 ganglion cell, 1 Müller glia, 1 RPE

col = build_retinal_column(regime=:scotopic)
sidx = StateIndex(col)

println("\nRetinal column built:")
println("  Rods:       $(col.pop.n_rod)")
println("  Cones:      $(col.pop.n_cone)")
println("  HCs:        $(col.pop.n_hc)")
println("  ON-BCs:     $(col.pop.n_on)")
println("  OFF-BCs:    $(col.pop.n_off)")
println("  A2 amac:    $(col.pop.n_a2)")
println("  GABA amac:  $(col.pop.n_gaba)")
println("  DA amac:    $(col.pop.n_dopa)")
println("  GCs:        $(col.pop.n_gc)")
println("  Müller:     $(col.pop.n_muller)")
println("  RPE:        $(col.pop.n_rpe)")
println("  Total ODEs: $(sidx.total)")

# --- Section 3: Simulate a Dim Flash (Scotopic) ---
# A dim flash primarily activates rods. We expect to see:
#   - a-wave: negative deflection from photoreceptor hyperpolarization
#   - b-wave: positive deflection from ON-bipolar depolarization
#   - OPs: fast oscillations on the b-wave ascending limb (A2↔GABA network)

println("\n--- Simulating dim scotopic flash ---")
println("Intensity: 10 photons/µm²/ms, Duration: 10 ms")
println("Simulation window: 1000 ms")

result_dim = simulate_flash(intensity=10.0, duration=10.0, t_total=1000.0)
println("Done! $(length(result_dim.t)) timepoints saved.")

# --- Section 4: Plot the ERG ---
# The ERG (electroretinogram) is a field potential recorded at the cornea.
# It is the weighted sum of all transmembrane currents in the retina.

println("\nPlotting ERG...")
fig_erg = plot_erg(result_dim, show_components=true)
display(fig_erg)
# Uncomment to save: save("dim_flash_erg.png", fig_erg)

# --- Section 5: Look at Cell Voltages ---
# Each cell type has distinct dynamics. Photoreceptors hyperpolarize in light,
# ON-bipolars depolarize (sign inversion via mGluR6), and amacrines oscillate.

println("\nPlotting cell membrane potentials...")
fig_v = plot_cell_voltages(result_dim,
    cell_types=[:rod, :cone, :on_bc, :off_bc, :a2, :gaba_ac, :gc])
display(fig_v)

# --- Section 6: Intensity Series ---
# The a-wave and b-wave amplitudes follow a Naka-Rushton (sigmoidal) function
# when plotted against log intensity. Let's run several intensities.

println("\n--- Running intensity series ---")
intensities = [1.0, 10.0, 100.0, 1000.0, 10000.0]
results = []

for I in intensities
    println("  Intensity = $I ...")
    r = simulate_flash(intensity=I, duration=10.0, t_total=1000.0)
    push!(results, r)
end
println("All intensities complete.")

# --- Section 7: Intensity-Response Plot ---
println("\nPlotting intensity-response function...")
fig_ir = plot_intensity_response(results, measure=:b_wave)
display(fig_ir)

# --- Section 8: Extract Oscillatory Potentials ---
# OPs are fast oscillations (100-160 Hz) generated by the A2↔GABA reciprocal
# inhibitory network. They ride on the ascending limb of the b-wave.
# Extract by bandpass filtering at 75-300 Hz.

println("\nExtracting oscillatory potentials...")
fig_ops = plot_ops(result_dim, time_window=(180.0, 280.0))
display(fig_ops)

# --- Section 9: Bright Flash (Photopic-like) ---
# A very bright flash saturates rods and drives cones.
# We expect faster kinetics and a more prominent OFF response (d-wave).

println("\n--- Simulating bright flash ---")
result_bright = simulate_flash(intensity=50000.0, duration=10.0, t_total=1000.0)
fig_bright = plot_erg(result_bright, show_components=true)
display(fig_bright)

# --- Section 10: Long Simulation with c-wave ---
# The c-wave is generated by the RPE and peaks at 2-5 seconds.
# Need a longer simulation window to see it.

println("\n--- Simulating with c-wave (5 second window) ---")
result_long = simulate_flash(intensity=1000.0, duration=10.0, t_total=5000.0, dt_save=1.0)
fig_long = plot_erg(result_long, show_components=true)
display(fig_long)

# --- Section 11: Exploring Parameters ---
# The model is fully parameterized. You can modify any cell type's parameters
# using Setfield.jl's @set macro.

println("\n--- Parameter exploration examples ---")
println("Try in the REPL:")
println("  using Setfield")
println("  col = build_retinal_column()")
println("  col = @set col.a2_params.phi = 0.3     # faster A2 dynamics → shift OP frequency")
println("  col = @set col.mglur6_params.tau_mGluR6 = 50.0  # slower b-wave")
println("  col = @set col.rod_params.g_H = 4.0    # stronger I_H → bigger nose")

println("\n" * "=" ^ 60)
println("  Walkthrough complete!")
println("=" ^ 60)
